### ISSUE TITLE
Segfault when Scheme not defined

### ISSUE THREAD

**Issue by trimoq** [apache/incubator-openwhisk-wskdeploy#1050]
Wskdeploy crashes with a Segfault when the URL Scheme is not defined in `apihost`:

- version: 0.10.0-incubating
- manifest: the sample from [the getting-started-guide](https://openwhisk.apache.org/documentation.html#wskdeploy)

To reproduce the segfault:
```
wsk property set --auth ....
wsk property set --apihost 192.168.55.5:31001
wskdeploy
```
in contrast, the following works:
```
wsk property set --auth ....
wsk property set --apihost https://192.168.55.5:31001
wskdeploy
```

The segfault seems to originate [this code](https://github.com/apache/incubator-openwhisk-client-go/blob/47ad3426a4e3632fd17d859303f4074ae7b959ff/whisk/wskprops.go#L72) 

the error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x72e81a]

goroutine 1 [running]:
github.com/apache/incubator-openwhisk-wskdeploy/vendor/github.com/apache/incubator-openwhisk-client-go/whisk.GetUrlBase(0x7fff505c4404, 0x12, 0x1, 0x1, 0xc4201269c0)
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/vendor/github.com/apache/incubator-openwhisk-client-go/whisk/wskprops.go:72 +0xea
github.com/apache/incubator-openwhisk-wskdeploy/vendor/github.com/apache/incubator-openwhisk-client-go/whisk.NewClient(0xc420256180, 0xc420226c80, 0x0, 0x0, 0xc420226c80)
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/vendor/github.com/apache/incubator-openwhisk-client-go/whisk/client.go:130 +0x778
github.com/apache/incubator-openwhisk-wskdeploy/deployers.glob..func5(0xc420226c80, 0x15, 0x0, 0x0)
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/deployers/whiskclient.go:81 +0x53
github.com/apache/incubator-openwhisk-wskdeploy/cmd.Deploy(0xb09ba0, 0x1, 0xc420116238)
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/cmd/root.go:231 +0x4a7
github.com/apache/incubator-openwhisk-wskdeploy/cmd.RootCmdImp(0xb09ba0, 0xc42010c7e0, 0x0, 0x6, 0x0, 0x0)
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/cmd/root.go:51 +0x2b
github.com/apache/incubator-openwhisk-wskdeploy/vendor/github.com/spf13/cobra.(*Command).execute(0xb09ba0, 0xc420092010, 0x6, 0x6, 0xb09ba0, 0xc420092010)
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/vendor/github.com/spf13/cobra/command.go:632 +0x3e8
github.com/apache/incubator-openwhisk-wskdeploy/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xb09ba0, 0x0, 0xb0a200, 0x1)
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/vendor/github.com/spf13/cobra/command.go:722 +0x2fe
github.com/apache/incubator-openwhisk-wskdeploy/vendor/github.com/spf13/cobra.(*Command).Execute(0xb09ba0, 0x7, 0x7)
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/apache/incubator-openwhisk-wskdeploy/cmd.Execute()
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/cmd/root.go:65 +0xe4
main.main()
	/home/travis/gopath/src/github.com/apache/incubator-openwhisk-wskdeploy/main.go:26 +0x20
```
Do we have to set the scheme in the apihost or should the code in `GetUrlBase` handle this correctly?

**Comment by trimoq** [comment]
Ok, according to the [go docs](https://golang.org/src/net/url/url.go?s=13181:13220#L469):

> Trying to parse a hostname and path without a scheme is invalid but may not necessarily return an error, due to parsing ambiguities. 

If the code in the [go client](https://github.com/apache/incubator-openwhisk-client-go/blob/47ad3426a4e3632fd17d859303f4074ae7b959ff/whisk/wskprops.go#L72) is modified to the following, a missing schema is not causing a segfault anymore.

```go
// was:    if len(url.Scheme) == 0 || len(url.Host) == 0 { 
if url==nil || len(url.Scheme) == 0 || len(url.Host) == 0 { 
  urlBase = fmt.Sprintf("https://%s/api", host)
  url, err = url.Parse(urlBase)
}
```
Does this has to be fixed or must the user set the scheme in the first place?

**Comment by dgrove-oss** [comment]
The user should not be required to set the scheme.   Sorry this issue got overlooked for two months.
