### ISSUE TITLE
Action created with .zip file fails with SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by pritidesai** [apache/incubator-openwhisk-wskdeploy#273]
I tried a simple workflow here:

**1. Created an action for nodejs runtime**

```
cat index.js
function helloworld(params) {
    return {payload: 'Hello World!'};
}

exports.main = helloworld;
```

**2. Created zip file out of this single action file `index.js`:**

```
 zip helloworld.zip index.js
```

**3. Created manifest file with:**

```
package:
    name: helloworldzip
    actions:
        helloworld:
            location: src/helloworld.zip
            runtime: nodejs:6
```

**4. Deployed hello world action:**

```
bin/wskdeploy
         ____      ___                   _    _ _     _     _
        /\   \    / _ \ _ __   ___ _ __ | |  | | |__ (_)___| | __
   /\  /__\   \  | | | | '_ \ / _ \ '_ \| |  | | '_ \| / __| |/ /
  /  \____ \  /  | |_| | |_) |  __/ | | | |/\| | | | | \__ \   <
  \   \  /  \/    \___/| .__/ \___|_| |_|__/\__|_| |_|_|___/_|\_\
   \___\/              |_|

Packages:
Name: helloworldzip
    bindings:

  * action: helloworld
    bindings:
    annotations:


Triggers:

 Rules

Do you really want to deploy this? (y/N): y
2017/05/19 11:56:24 Deploying package helloworldzip ...
2017/05/19 11:56:25 Done!
2017/05/19 11:56:25 Deploying action helloworldzip/helloworld ...
2017/05/19 11:56:25 Done!

Deployment completed successfully.
```

**5. Invoke hello world action**

```
wsk action invoke helloworldzip/helloworld --blocking
ok: invoked <namespace>/helloworldzip/helloworld with id 15bdc301425b4c028df74311da45587a
{
    "activationId": "15bdc301425b4c028df74311da45587a",
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": "<namespace>/helloworldzip/helloworld"
        }
    ],
    "duration": 45,
    "end": 1495220208672,
    "logs": [],
    "name": "helloworld",
    "namespace": "<namespace>",
    "publish": false,
    "response": {
        "result": {
            "error": "Initialization has failed due to: SyntaxError: Invalid or unexpected token\n    at NodeActionRunner.init (/nodejsAction/runner.js:75:109)\n    at doInit (/nodejsAction/src/service.js:133:31)\n    at initCode (/nodejsAction/src/service.js:81:24)\n    at /nodejsAction/app.js:61:13\n    at Layer.handle [as handle_request] (/nodejsAction/node_modules/express/lib/router/layer.js:95:5)\n    at next (/nodejsAction/node_modules/express/lib/router/route.js:131:13)\n    at Route.dispatch (/nodejsAction/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/nodejsAction/node_modules/express/lib/router/layer.js:95:5)\n    at /nodejsAction/node_modules/express/lib/router/index.js:277:22\n    at Function.process_params (/nodejsAction/node_modules/express/lib/router/index.js:330:12)"
        },
        "status": "action developer error",
        "success": false
    },
    "start": 1495220208627,
    "subject": "<namespace>",
    "version": "0.0.1"
}
```

Running the same with wsk CLI:

**Create an action:**

```
wsk action create helloworldzip helloworld.zip --kind nodejs:6
ok: created action helloworldzip
```

**Invoking hello world:**

```
wsk action invoke helloworldzip --blocking
ok: invoked /<namespace>/helloworldzip with id 27a1621dd8db430abeaade0ec1d33b0c
{
    "activationId": "27a1621dd8db430abeaade0ec1d33b0c",
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": "<namespace>/helloworldzip"
        }
    ],
    "duration": 72,
    "end": 1495222791850,
    "logs": [],
    "name": "helloworldzip",
    "namespace": "<namespace>",
    "publish": false,
    "response": {
        "result": {
            "payload": "Hello World!"
        },
        "status": "success",
        "success": true
    },
    "start": 1495222791778,
    "subject": "<namespace>",
    "version": "0.0.1"
}
```

Tried with different combination of keys in manifest file but fails with same error:

**Without explicitly specifying runtime:**

```
package:
    name: helloworldzip
    actions:
        helloworld:
            location: src/helloworld.zip
```

**With `kind` keyword (not sure if its supported, looking into it):**

```
package:
    name: helloworldzip
    actions:
        helloworld:
            location: src/helloworld.zip
            kind: nodejs:6
```

@mrutkows @lzbj @houshengbo @daisy-ycguo

**Comment by pritidesai** [comment]
HTTP request is sent by `wskdeploy`, note unicode in `code`:

```Req Body
{{"name":"helloworldzip/helloworld","exec":{"kind":"nodejs:default","code":"PK\u0003\u0004\u0014\u0000\u0000\u0000\u0008\u0000\ufffdd\ufffdJո\ufffdDU\u0000\u0000\u0000b\u0000\u0000\u0000\u0008\u0000\u001c\u0000index.jsUT\t\u0000\u0003\ufffdI\u001fY\ufffdI\u001fYux\u000b\u0000\u0001\u0004\ufffd\u0001\u0000\u0000\u0004\u0014\u0000\u0000\u0000K+\ufffdK.\ufffd\ufffd\ufffdS\ufffdH\ufffd\ufffd\ufffd/\ufffd/\ufffdI\ufffd(H,J\ufffd-\ufffdT\ufffd\ufffdR\u0000\ufffd\ufffdԒҢ<\ufffd\ufffd\ufffd\ufffdʜ\ufffd\ufffd\u0014+\u0005u\u000f\ufffdR\ufffdp\ufffdZE\ufffdZk\ufffdZ.\ufffdԊ\ufffd\ufffd\ufffd\ufffdb\ufffd\ufffd\ufffd\ufffd<\u0005[$ì\ufffd\u0000PK\u0001\u0002\u001e\u0003\u0014\u0000\u0000\u0000\u0008\u0000\ufffdd\ufffdJո\ufffdDU\u0000\u0000\u0000b\u0000\u0000\u0000\u0008\u0000\u0018\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000\ufffd\ufffd\u0000\u0000\u0000\u0000index.jsUT\u0005\u0000\u0003\ufffdI\u001fYux\u000b\u0000\u0001\u0004\ufffd\u0001\u0000\u0000\u0004\u0014\u0000\u0000\u0000PK\u0005\u0006\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000N\u0000\u0000\u0000\ufffd\u0000\u0000\u0000\u0000\u0000"},"publish":false}
}
```

VS

Request Body when an action is created with `wsk' cli:

```
{{"namespace":"<namespace>","name":"helloworldzip","exec":{"kind":"nodejs:6","code":"UEsDBBQAAAAIAO9ks0rVuPFEVQAAAGIAAAAIABwAaW5kZXguanNVVAkAA/JJH1nySR9ZdXgLAAEE9QEAAAQUAAAASyvNSy7JzM9TyEjNyckvzy/KSdEoSCxKzC3WVKjmUgCCotSS0qI8heqCxMqc/MQUKwV1D5BShXCQWkX1WmuuWi6u1IqC/KKSYr3cxMw8BVskw6y5AFBLAQIeAxQAAAAIAO9ks0rVuPFEVQAAAGIAAAAIABgAAAAAAAEAAACkgQAAAABpbmRleC5qc1VUBQAD8kkfWXV4CwABBPUBAAAEFAAAAFBLBQYAAAAAAQABAE4AAACXAAAAAAA="}}
}
```

**Comment by mrutkows** [comment]
@pritidesai it looks like you have isolated an encoding error and can reference the CLI code to see what they do differently.  I would assume that at some point we are using a "string" type (some automatic conversion to unicode ) where the "code" should be treated as binary perhaps?

**Comment by mrutkows** [comment]
@pritidesai if this helps (and sure you could find this as well) the 
 incubator-openwhisk/tools/cli/go-whisk-cli/commands/action.go includes this fx where Go string is used from a readFile() then base64 encoded (and treated as a byte array):

```
func getExec(artifact string, kind string, isDocker bool, mainEntry string) (*whisk.Exec, error) {
    var err error
    var code string
    var exec *whisk.Exec

    ext := filepath.Ext(artifact)
    exec = new(whisk.Exec)

    if !isDocker || ext == ".zip" {
        code, err = readFile(artifact)

        if ext == ".zip" || ext == ".jar" {
            // Base64 encode the file
            code = base64.StdEncoding.EncodeToString([]byte(code))
            exec.Code = &code
        } else {
            exec.Code = &code
        }

        if err != nil {
            whisk.Debug(whisk.DbgError, "readFile(%s) error: %s\n", artifact, err)
            return nil, err
        }
    }
```
