### ISSUE TITLE
"report" command not working / is it still valid?

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-wskdeploy#582]
This looks like it initially was intended to be used perhaps towards some "verify" command; however, it is not used anywhere within the code and invoking it via the command line results in an exception.

```
$ ./wskdeploy report
----==== OpenWhisk Deployment Status ====----
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x13b928e]

goroutine 1 [running]:
github.com/apache/incubator-openwhisk-wskdeploy/cmd.printDeploymentInfo(0x0, 0x0, 0x1671240)
	/Users/Matt/go/src/github.com/apache/incubator-openwhisk-wskdeploy/cmd/report.go:86 +0x8e
github.com/apache/incubator-openwhisk-wskdeploy/cmd.glob..func6(0x16a2fa0, 0x16c2c58, 0x0, 0x0, 0x0, 0x0)
	/Users/Matt/go/src/github.com/apache/incubator-openwhisk-wskdeploy/cmd/report.go:49 +0x9e
github.com/spf13/cobra.(*Command).execute(0x16a2fa0, 0x16c2c58, 0x0, 0x0, 0x16a2fa0, 0x16c2c58)
	/Users/Matt/go/src/github.com/spf13/cobra/command.go:650 +0x457
github.com/spf13/cobra.(*Command).ExecuteC(0x16a31e0, 0xc4200aff78, 0x100670c, 0xc420072058)
	/Users/Matt/go/src/github.com/spf13/cobra/command.go:729 +0x339
github.com/spf13/cobra.(*Command).Execute(0x16a31e0, 0x0, 0x0)
	/Users/Matt/go/src/github.com/spf13/cobra/command.go:688 +0x2b
github.com/apache/incubator-openwhisk-wskdeploy/cmd.Execute()
	/Users/Matt/go/src/github.com/apache/incubator-openwhisk-wskdeploy/cmd/root.go:66 +0x40
main.main()
	/Users/Matt/go/src/github.com/apache/incubator-openwhisk-wskdeploy/main.go:26 +0x20

```

We should discuss if this is still valid/valuable... if it is we need to make it work OR remove it.  At minimum we should disable it in the near term.

**Comment by houshengbo** [comment]
@mrutkows This is an obvious bug, which needs a quick fix.
